add_library(pcsx2core STATIC
	BuildVersion.cpp
	Cache.cpp
	CDVD/CDVD.cpp
	CDVD/CDVDcommon.cpp
	CDVD/CDVDdiscReader.cpp
	CDVD/CDVDdiscThread.cpp
	CDVD/CDVDisoReader.cpp
	CDVD/FlatFileReader.cpp
	CDVD/InputIsoFile.cpp
	CDVD/IsoHasher.cpp
	CDVD/IsoReader.cpp
	CDVD/OutputIsoFile.cpp
	CDVD/Ps1CD.cpp
	CDVD/ThreadedFileReader.cpp
	COP0.cpp
	COP2.cpp
	Counters.cpp
	DebugTools/BiosDebugData.cpp
	DebugTools/Breakpoints.cpp
	DebugTools/DebugInterface.cpp
	DebugTools/DisR3000A.cpp
	DebugTools/DisR5900asm.cpp
	DebugTools/DisVU0Micro.cpp
	DebugTools/DisVU1Micro.cpp
	DebugTools/DisassemblyManager.cpp
	DebugTools/ExpressionParser.cpp
	DebugTools/MIPSAnalyst.cpp
	DebugTools/MipsAssembler.cpp
	DebugTools/MipsAssemblerTables.cpp
	DebugTools/MipsStackWalk.cpp
	DebugTools/SymbolGuardian.cpp
	DebugTools/SymbolImporter.cpp
	Dmac.cpp
	Elfheader.cpp
	FPU.cpp
	FiFo.cpp
	GS.cpp
	Gif.cpp
	Gif_Logger.cpp
	Gif_Unit.cpp
	Host.cpp
	Hw.cpp
	HwRead.cpp
	HwWrite.cpp
	INISettingsInterface.cpp
	IPU/IPU.cpp
	IPU/IPU_Fifo.cpp
	IPU/IPU_MultiISA.cpp
	IPU/IPUdither.cpp
	IPU/IPUdma.cpp
	IPU/yuv2rgb.cpp
	Interpreter.cpp
	IopBios.cpp
	IopCounters.cpp
	IopDma.cpp
	IopGte.cpp
	IopHw.cpp
	IopIrq.cpp
	IopMem.cpp
	LayeredSettingsInterface.cpp
	MMI.cpp
	MTVU.cpp
	Mdec.cpp
	Memory.cpp
	Pcsx2Config.cpp
	PerformanceMetrics.cpp
	R3000A.cpp
	R3000AInterpreter.cpp
	R3000AOpcodeTables.cpp
	R5900.cpp
	R5900OpcodeImpl.cpp
	R5900OpcodeTables.cpp
	SIO/Pad/PadBase.cpp
	SIO/Pad/PadNotConnected.cpp
	SIO/Memcard/MemoryCardFile.cpp
	SIO/Memcard/MemoryCardProtocol.cpp
	SIO/Multitap/MultitapProtocol.cpp
	SIO/Sio.cpp
	SIO/Sio0.cpp
	SIO/Sio2.cpp
	SPU2/ADSR.cpp
	SPU2/Debug.cpp
	SPU2/Dma.cpp
	SPU2/Mixer.cpp
	SPU2/ReadInput.cpp
	SPU2/RegTable.cpp
	SPU2/Reverb.cpp
	SPU2/ReverbResample.cpp
	SPU2/Wavedump_wav.cpp
	SPU2/spu2.cpp
	SPU2/spu2freeze.cpp
	SPU2/spu2sys.cpp
	SPR.cpp
	ShiftJisToUnicode.cpp
	Sif.cpp
	Sif0.cpp
	Sif1.cpp
	SourceLog.cpp
	StateWrapper.cpp
	VU0.cpp
	VU0micro.cpp
	VU0microInterp.cpp
	VU1micro.cpp
	VU1microInterp.cpp
	VUflags.cpp
	VUmicro.cpp
	VUmicroMem.cpp
	VUops.cpp
	Vif.cpp
	Vif0_Dma.cpp
	Vif1_Dma.cpp
	Vif1_MFIFO.cpp
	Vif_Codes.cpp
	Vif_Transfer.cpp
	Vif_Unpack.cpp
	ps2/BiosTools.cpp
	ps2/Iop/IopHwRead.cpp
	ps2/Iop/IopHwWrite.cpp
	ps2/Iop/PsxBios.cpp
	ps2/pgif.cpp
	sif2.cpp
	vita/VitaAudioStream.cpp
	vita/A32Emitter.cpp
	vita/VitaCaptureDisabled.cpp
	vita/VitaCdvdDevice.cpp
	vita/VitaCpuProviders.cpp
	vita/VitaDisabledDevices.cpp
	vita/VitaEeBlockCompiler.cpp
	vita/VitaEeExecutor.cpp
	vita/VitaGsMailbox.cpp
	vita/VitaHostSurface.cpp
	vita/VitaPad.cpp
	vita/VitaVifInterpreter.cpp
	vita/VitaVmState.cpp
	vtlb.cpp
)

set(VITASX2_GIT_TAG "vitasx2-ng")
set(VITASX2_GIT_REV "vitasx2-ng-pcsx2-fe3ce7f57")
set(VITASX2_GIT_HASH "fe3ce7f578e2dd39418ef358d84804d290e91bc1")
set(VITASX2_GIT_DATE "2026-07-01")
configure_file(vita/svnrev.h.in "${CMAKE_CURRENT_BINARY_DIR}/svnrev.h" @ONLY)

target_include_directories(pcsx2core PUBLIC
	"${CMAKE_CURRENT_SOURCE_DIR}/.."
	"${CMAKE_CURRENT_SOURCE_DIR}"
	"${CMAKE_CURRENT_BINARY_DIR}"
	"${CMAKE_SOURCE_DIR}/3rdparty/include"
)

target_compile_definitions(pcsx2core PUBLIC
	PCSX2_CORE=1
	VITASX2_VITA=1
)

target_compile_options(pcsx2core PRIVATE
	-Wno-invalid-offsetof
	-Wno-missing-braces
	-Wno-multichar
	-Wno-parentheses
	-Wno-unknown-pragmas
)

target_link_libraries(pcsx2core PUBLIC
	common
	fmt::fmt
	fast_float
	simpleini
	rapidjson
	xxhash
	ccc
	demanglegnu
)
